#include "MasterManifest.h"

// AUTO-GENERATED from manifest.csv
// Keep this table in sync with the SD /manifest.csv on the Sides.

const MasterClipMeta MASTER_CLIPS[] = {
  // BASE: animals
  {1001, "animals", "farm", "chicken"},
  {1002, "animals", "farm", "chicken"},
  {1003, "animals", "farm", "chicken"},
  {1004, "animals", "farm", "chicken"},
  {1005, "animals", "farm", "cow"},
  {1006, "animals", "farm", "cow"},
  {1007, "animals", "farm", "cow"},
  {1008, "animals", "farm", "duck"},
  {1009, "animals", "farm", "duck"},
  {1010, "animals", "farm", "duck"},
  {1011, "animals", "farm", "horse"},
  {1012, "animals", "farm", "horse"},
  {1013, "animals", "farm", "horse"},
  {1014, "animals", "farm", "pigs"},
  {1015, "animals", "farm", "pigs"},
  {1016, "animals", "farm", "pigs"},
  {1017, "animals", "farm", "sheep"},
  {1018, "animals", "farm", "sheep"},
  {1101, "animals", "jungle", "birds"},
  {1102, "animals", "jungle", "birds"},
  {1103, "animals", "jungle", "birds"},
  {1104, "animals", "jungle", "elephant"},
  {1105, "animals", "jungle", "elephant"},
  {1106, "animals", "jungle", "frogs"},
  {1107, "animals", "jungle", "frogs"},
  {1108, "animals", "jungle", "frogs"},
  {1109, "animals", "jungle", "tigers"},
  {1110, "animals", "jungle", "tigers"},
  {1201, "animals", "pets", "dogs"},
  {1202, "animals", "pets", "dogs"},
  {1203, "animals", "pets", "dogs"},
  {1204, "animals", "pets", "cats"},
  {1205, "animals", "pets", "cats"},
  {1206, "animals", "pets", "cats"},
  // BASE: tones
  {5001, "tones", "simple", "low_beep"},
  {5002, "tones", "simple", "mid_beep"},
  {5003, "tones", "simple", "high_beep"},
  {5101, "tones", "sweep", "up_short"},
  {5102, "tones", "sweep", "down_short"},
  {5103, "tones", "sweep", "siren_slow"},
  {5201, "tones", "noise", "burst_short"},
  {5202, "tones", "noise", "burst_long"},
  {5301, "tones", "rhythm", "double_click"},
  {5302, "tones", "rhythm", "triple_beep"},
  // BASE: humans
  {2001, "humans", "male", "sigh"},
  {2002, "humans", "male", "sigh"},
  {2003, "humans", "male", "sigh"},
  {2004, "humans", "male", "sneeze"},
  {2005, "humans", "male", "sneeze"},
  {2006, "humans", "male", "sneeze"},
  {2007, "humans", "male", "snore"},
  {2008, "humans", "male", "snore"},
  {2009, "humans", "male", "snore"},
  {2010, "humans", "male", "whistle"},
  {2011, "humans", "male", "whistle"},
  {2012, "humans", "male", "whistle"},
  {2013, "humans", "male", "yawn"},
  {2014, "humans", "male", "yawn"},
  {2015, "humans", "male", "yawn"},
  {2016, "humans", "male", "cough"},
  {2017, "humans", "male", "cough"},
  {2018, "humans", "male", "laugh"},
  {2019, "humans", "male", "laugh"},
  {2101, "humans", "female", "laugh"},
  // BASE: instruments
  {3001, "instruments", "guitar", "electric"},
  {3002, "instruments", "guitar", "electric"},
  {3003, "instruments", "guitar", "electric"},
  {3004, "instruments", "guitar", "electric"},
  {3005, "instruments", "guitar", "acoustic"},
  {3006, "instruments", "guitar", "acoustic"},
  {3007, "instruments", "guitar", "acoustic"},
  {3201, "instruments", "drum", "drumkit"},
  {3202, "instruments", "drum", "drumkit"},
  {3203, "instruments", "drum", "drumkit"},
  {3204, "instruments", "drum", "djembe"},
  {3205, "instruments", "drum", "djembe"},
  {3206, "instruments", "drum", "bongo"},
  {3207, "instruments", "drum", "bongo"},
  {3301, "instruments", "classical", "piano"},
  {3302, "instruments", "classical", "piano"},
  {3303, "instruments", "classical", "piano"},
  {3304, "instruments", "classical", "saxophone"},
  {3305, "instruments", "classical", "saxophone"},
  {3306, "instruments", "classical", "saxophone"},
  {3307, "instruments", "classical", "trumpet"},
  {3311, "instruments", "classical", "trumpet"},
  {3312, "instruments", "classical", "trumpet"},
  {3308, "instruments", "classical", "violin"},
  {3309, "instruments", "classical", "violin"},
  {3310, "instruments", "classical", "violin"},
  // BASE: tools
  {4001, "tools", "electric", "chainsaw"},
  {4002, "tools", "electric", "chainsaw"},
  {4003, "tools", "electric", "chainsaw"},
  {4004, "tools", "electric", "chopsaw"},
  {4005, "tools", "electric", "chopsaw"},
  {4006, "tools", "electric", "lawnmower"},
  {4007, "tools", "electric", "lawnmower"},
  {4008, "tools", "electric", "anglegrinder"},
  {4009, "tools", "electric", "drill"},
  {4101, "tools", "manual", "wrench"},
  {4102, "tools", "manual", "saw"},
  {4103, "tools", "manual", "hammer"},
  // BASE: vehicles
  {5019, "vehicles", "grounded", "enginestart"},
  {5020, "vehicles", "grounded", "enginestart"},
  {5021, "vehicles", "grounded", "enginestart"},
  {5004, "vehicles", "grounded", "horn"},
  {5005, "vehicles", "grounded", "horn"},
  {5006, "vehicles", "grounded", "horn"},
  {5007, "vehicles", "grounded", "race"},
  {5008, "vehicles", "grounded", "race"},
  {5009, "vehicles", "grounded", "race"},
  {5010, "vehicles", "grounded", "skid"},
  {5011, "vehicles", "grounded", "skid"},
  {5012, "vehicles", "grounded", "skid"},
  {5013, "vehicles", "grounded", "turnsignal"},
  {5014, "vehicles", "grounded", "turnsignal"},
  {5015, "vehicles", "grounded", "turnsignal"},
  {5016, "vehicles", "grounded", "train"},
  {5017, "vehicles", "grounded", "policesiren"},
  {5018, "vehicles", "grounded", "policesiren"},
  {5203, "vehicles", "arial", "airplane"},
  {5204, "vehicles", "arial", "helicopter"},
  // BASE: occassions
  {6001, "occassions", "halloween", "ghost"},
  {6002, "occassions", "halloween", "ghost"},
  {6003, "occassions", "halloween", "zombie"},
  {6004, "occassions", "halloween", "zombie"},
  {6005, "occassions", "halloween", "zombie"},
  {6006, "occassions", "halloween", "thunder"},
  {6007, "occassions", "halloween", "thunder"},
  {6008, "occassions", "halloween", "thunder"},
  {6009, "occassions", "halloween", "spookylaugh"},
  {6010, "occassions", "halloween", "spookylaugh"},
  {6011, "occassions", "halloween", "spookylaugh"},
  {6101, "occassions", "christmas", "jinglebells"},
  {6102, "occassions", "christmas", "jinglebells"},
  {6103, "occassions", "christmas", "jinglebells"},
  {6104, "occassions", "christmas", "walkinginsnow"},
  {6105, "occassions", "christmas", "walkinginsnow"},
  {6106, "occassions", "christmas", "walkinginsnow"},
  {6107, "occassions", "christmas", "hohoho"},
  {6108, "occassions", "christmas", "hohoho"},
  {6109, "occassions", "christmas", "hohoho"},
  {6110, "occassions", "christmas", "carolers"},
  {6201, "occassions", "birthday", "happybirthday"},
  {6202, "occassions", "birthday", "blowoutcandles"},
  {6203, "occassions", "birthday", "blowoutcandles"},
  {6204, "occassions", "birthday", "blowoutcandles"},
  {6205, "occassions", "birthday", "noisemaker"},
};

const size_t MASTER_CLIP_COUNT = sizeof(MASTER_CLIPS) / sizeof(MASTER_CLIPS[0]);

const MasterClipMeta* MasterManifest_find(uint16_t id) {
  for (size_t i = 0; i < MASTER_CLIP_COUNT; i++) {
    if (MASTER_CLIPS[i].id == id) return &MASTER_CLIPS[i];
  }
  return nullptr;
}
